spring.application.name=gateway

server.port=8001

#make the entire app log level to debug to see the inner details
#logging.level.root=DEBUG


#example to config opd service to gateway using prop file
#spring.cloud.gateway.mvc.routes[0].id=opd-service
#spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8080
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/hello,/consultation/**

