spring.application.name=gateway

server.port=8001

#make the entire app log level to debug to see the inner details
#logging.level.root=DEBUG

# Enable debug logs for Spring Security
logging.level.org.springframework.security=TRACE
logging.level=DEBUG


#example to config opd service to gateway using prop file
#spring.cloud.gateway.mvc.routes[0].id=opd-service
#spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8080
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/hello,/consultation/**

#configure oauth configuration to use google:
spring.security.oauth2.client.registration.google.client-id=779266497201-piokbeqgllk9pgq26isrtq3cck1km8d0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
spring.security.oauth2.client.registration.google.scope=openid,profile,email

